# Generated by Django 2.2.5 on 2020-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.TextField(default='{}'),
        ),
    ]
