# Generated by Django 2.2.5 on 2020-02-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20200131_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='hoster',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.TextField(default={}),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_events',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.TextField(default='[]'),
        ),
    ]
