# Generated by Django 2.2.5 on 2020-02-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20200202_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.FileField(default='/', upload_to=''),
            preserve_default=False,
        ),
    ]
