# Generated by Django 2.2.5 on 2020-02-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(upload_to='usr_img'),
        ),
    ]
