# Generated by Django 2.2.5 on 2020-02-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_auto_20200208_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='events',
            field=models.TextField(default='[]'),
        ),
    ]
